### PR TITLE
Added events to the MCP and Robot

### PR DESCRIPTION
**Pull request by lorenwest**
* Added "events" attribute to the MCP, Robot, and Device
* Added event discovery endpoints to match command discovery endpoints
* Added event GET endpoints at the MCP and Robot level to match the GET endpoint at the Device
* Provided consistent API ordering at all 3 levels:
  * Command discovery
  * Event discovery
  * Command POST
  * Event GET

### CODE REVIEW

**Comment by deadprogram** [comment]
Sorry, I meant to merge this already. Thanks for the contribution!

**Comment by lorenwest** [comment]
Would you like help implementing?  I'm working with cylon and wouldn't mind adding this support.

**Comment by deadprogram** [comment]
I think @stewart has already been doing some work on it, and will probably commit something next week. Once he has his commits in place, you can perhaps provide some feedback or additional implementation, how does that sound?

**Comment by lorenwest** [comment]
Excellent.

**Pull request merged**
